# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskagitmakas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1079, 749)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, -30, 1131, 821))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1000_F_115575013_bGdWptTXmcWnYIYT3W9JyDWi4mTQHyGj.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.aigoruntu = QtWidgets.QGraphicsView(Form)
        self.aigoruntu.setGeometry(QtCore.QRect(30, 150, 401, 421))
        self.aigoruntu.setObjectName("aigoruntu")
        self.kullanicigoruntu = QtWidgets.QGraphicsView(Form)
        self.kullanicigoruntu.setGeometry(QtCore.QRect(650, 150, 401, 421))
        self.kullanicigoruntu.setObjectName("kullanicigoruntu")
        self.oyna = QtWidgets.QPushButton(Form)
        self.oyna.setGeometry(QtCore.QRect(460, 590, 161, 131))
        self.oyna.setObjectName("oyna")
        self.ai = QtWidgets.QLineEdit(Form)
        self.ai.setGeometry(QtCore.QRect(160, 600, 113, 21))
        self.ai.setObjectName("ai")
        self.kullanici = QtWidgets.QLineEdit(Form)
        self.kullanici.setGeometry(QtCore.QRect(790, 600, 113, 21))
        self.kullanici.setObjectName("kullanici")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(240, 40, 601, 51))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(510, 400, 61, 41))
        self.label_2.setObjectName("label_2")
        self.aiskor = QtWidgets.QLCDNumber(Form)
        self.aiskor.setGeometry(QtCore.QRect(440, 380, 64, 101))
        self.aiskor.setObjectName("aiskor")
        self.kullaniciskor = QtWidgets.QLCDNumber(Form)
        self.kullaniciskor.setGeometry(QtCore.QRect(570, 380, 64, 101))
        self.kullaniciskor.setObjectName("kullaniciskor")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.oyna.setText(_translate("Form", "OYNA"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">TAŞ-KAĞIT-MAKAS OYUNU</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">-</span></p></body></html>"))
